[green_agent]
agentbeats_id = "019b7f6a-3c4a-7932-b620-8f692e21ae5c"
env = { LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "a"
env = {}

[[participants]]
agentbeats_id = ""
name = "b"
env = {}

[config]
num_conversations_rounds = 5
num_rounds = 10
